# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [23]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/GuiMesc/IA---Exercicio-07---Rede-Neural-Artificial-Perceptron/main/diabetes.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8]) #numero de colunas do arquivo csv

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1

### Pré-processamento de Dados

In [24]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.MinMaxScaler()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não

Pregnancies = lb.fit_transform(np.array(base_Treinamento[:,0]).reshape(-1,1))  

Glucose = lb.fit_transform(np.array(base_Treinamento[:,1]).reshape(-1,1))  

BloodPressure = lb.fit_transform(np.array(base_Treinamento[:,2]).reshape(-1,1))  

SkinThickness = lb.fit_transform(np.array(base_Treinamento[:,3]).reshape(-1,1))  

Insulin = lb.fit_transform(np.array(base_Treinamento[:,4]).reshape(-1,1))  

BMI = lb.fit_transform(np.array(base_Treinamento[:,5]).reshape(-1,1))  

DiabetesPedigreeFunction = lb.fit_transform(np.array(base_Treinamento[:,6]).reshape(-1,1))  

Age = lb.fit_transform(np.array(base_Treinamento[:,7]).reshape(-1,1))  

Outcome = lb.fit_transform(np.array(base_Treinamento[:,8]).reshape(-1,1))  

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((Outcome))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do Neurônio Perceptron

In [25]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.736


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição a partir de base de dados (.csv)

In [32]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/GuiMesc/IA---Exercicio-07---Rede-Neural-Artificial-Perceptron/main/BaseTeste.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:7])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[9.000e+00 1.000e+02 5.500e+01 2.700e+01 1.500e+02 3.150e+01 5.270e-01
  4.000e+01]
 [5.000e+00 7.000e+01 6.300e+01 2.900e+01 1.000e+02 2.160e+01 1.730e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  2.000e+01]
 [0.000e+00 1.200e+02 6.000e+01 2.300e+01 9.400e+01 2.510e+01 1.500e-01
  2.100e+01]
 [0.000e+00 1.100e+02 4.000e+01 3.500e+01 1.200e+02 4.310e+01 2.288e+00
  3.000e+01]]
---------------------------------
Atributos de Entrada
---------------------------------
[[9.000e+00 1.000e+02 5.500e+01 2.700e+01 1.500e+02 3.150e+01 5.270e-01]
 [5.000e+00 7.000e+01 6.300e+01 2.900e+01 1.000e+02 2.160e+01 1.730e-01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01]
 [0.000e+00 1.200e+02 6.000e+01 2.300e+01 9.400e+01 2.510e+01 1.500e-01]
 [0.000e+00 1.100e+02 4.000e+01 3.500e+01 1.200e+02 4.310e+01 2.288e+00]]


### Pré-processamento de Dados

In [34]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.MinMaxScaler()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
Pregnancies = lb.fit_transform(np.array(base_Treinamento[:,0]).reshape(-1,1))  

Glucose = lb.fit_transform(np.array(base_Treinamento[:,1]).reshape(-1,1))  

BloodPressure = lb.fit_transform(np.array(base_Treinamento[:,2]).reshape(-1,1))  

SkinThickness = lb.fit_transform(np.array(base_Treinamento[:,3]).reshape(-1,1))  

Insulin = lb.fit_transform(np.array(base_Treinamento[:,4]).reshape(-1,1))  

BMI = lb.fit_transform(np.array(base_Treinamento[:,5]).reshape(-1,1))  

DiabetesPedigreeFunction = lb.fit_transform(np.array(base_Treinamento[:,6]).reshape(-1,1))  

Age = lb.fit_transform(np.array(base_Treinamento[:,7]).reshape(-1,1))

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]


### Predição da Base

In [35]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1.
 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0.
 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1.
 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1.
 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1.
 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1.
 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 